### ISSUE TITLE
Hierarchical annotations

### ISSUE THREAD

**Issue by jentiger82** [lcmmichielsen/treeArches-reproducibility#1]
I have a question regarding the learning of the cell type hierarchy. I am working with brain tissue. I for example can have 3 levels of annotation: 1) Neuron and Non-neuronal, 2) glutamatergic neurons and gabaergic neurons, and 3) CA1 pyramidal neurons, CA2 pyramidal neurons, ... In my metadata this would correspond to different entries ('level1','level2','level3'). How do I approach this if I want to use treeArches to build a tree from these different hierarchies (as for the HCLA example)? Would it be sequential by updating the tree with each new level?

Thanks, Jenny

**Comment by lcmmichielsen** [comment]
Are these annotations corresponding to three different datasets or different annotations levels belonging to one dataset?

In the first case, you could use the PBMC tutorial as an example. There we also show how to learn the hierarchy from multiple datasets. You can input the three datasets in one go and treeArches will handle that the tree is updated sequentially.

In the second case, there is not much to learn, since you already know how the annotations relate to each other. In that case, you could just create the tree and train it (see the basic tutorial in the scHPL documentation).

Let me know whether this is clear and you have any other questions!
